import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.scss";
import Script from "next/script";
import TopNavbar from "@/components/top-nav-bar";
import AsideSidebar from "@/components/aside-sidebar";

const inter = Inter({ weight: ["400", "500", "600"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNavbar/>
        <AsideSidebar/>
        <div className="mt-16 mb-10">{children}</div>
        </body>
      <Script  src="/script.js"></Script>
    </html>
  );
}
